// Maps common mood/keyword searches to TMDB genre name fragments.
// Values are arrays since some genres have compound names (e.g. TV's "Sci-Fi & Fantasy").
export const GENRE_ALIASES = {
  funny: ["Comedy"],
  comedy: ["Comedy"],
  hilarious: ["Comedy"],
  action: ["Action"],
  scary: ["Horror"],
  horror: ["Horror"],
  spooky: ["Horror"],
  sad: ["Drama"],
  drama: ["Drama"],
  emotional: ["Drama"],
  romantic: ["Romance"],
  romance: ["Romance"],
  love: ["Romance"],
  thriller: ["Thriller"],
  suspense: ["Thriller"],
  family: ["Family", "Kids"],
  kids: ["Family", "Kids"],
  animated: ["Animation"],
  animation: ["Animation"],
  cartoon: ["Animation"],
  documentary: ["Documentary"],
  docu: ["Documentary"],
  crime: ["Crime"],
  fantasy: ["Fantasy"],
  mystery: ["Mystery"],
  war: ["War"],
  western: ["Western"],
  musical: ["Music"],
  music: ["Music"],
  adventure: ["Adventure"],
  scifi: ["Science Fiction", "Sci-Fi"],
  "sci-fi": ["Science Fiction", "Sci-Fi"],
  "science fiction": ["Science Fiction", "Sci-Fi"],
  history: ["History"],
  historical: ["History"],
};