export const DUMMY_NOTIFICATIONS = [
  {
    id: 1,
    type: "new_release",
    title: "New episode released",
    message: '"Stranger Things" Season 5 Episode 3 is now available to watch.',
    time: "2 hours ago",
    unread: true,
  },
  {
    id: 2,
    type: "recommendation",
    title: "Recommended for you",
    message: "Because you watched action thrillers, we think you'll like \"The Extraction Point.\"",
    time: "5 hours ago",
    unread: true,
  },
  {
    id: 3,
    type: "leaving_soon",
    title: "Leaving soon",
    message: '"Midnight Runner" will leave NetflixGPT on August 15. Watch it before it\'s gone.',
    time: "1 day ago",
    unread: true,
  },
  {
    id: 4,
    type: "reminder",
    title: "Continue watching",
    message: 'You\'re halfway through "Ocean\'s Legacy" — pick up where you left off.',
    time: "2 days ago",
    unread: false,
  },
  {
    id: 5,
    type: "new_release",
    title: "New season added",
    message: '"Desert Storm Chronicles" Season 2 just dropped. All episodes available now.',
    time: "3 days ago",
    unread: false,
  },
  {
    id: 6,
    type: "account",
    title: "Profile updated",
    message: "Your avatar was successfully changed.",
    time: "5 days ago",
    unread: false,
  },
  {
    id: 7,
    type: "recommendation",
    title: "Top pick for you",
    message: '"Silent Horizon" is trending and matches your taste in sci-fi.',
    time: "1 week ago",
    unread: false,
  },
];